# Generated by Django 3.2.10 on 2021-12-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211228_0558'),
        ('store', '0002_auto_20211227_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
