# Generated by Django 3.2.10 on 2021-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211229_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigpackage',
            name='delivery',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gigpackage',
            name='package_type',
            field=models.CharField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Premium')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigpackage',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gigpackage',
            name='source_files',
            field=models.BooleanField(default=False),
        ),
    ]
