# Generated by Django 3.2.10 on 2021-12-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211229_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='price',
        ),
    ]
