# Generated by Django 3.2.10 on 2021-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_description_gigpackage_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigpackage',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
